version: "3"

# "Prod-like" compose file (uses prod Dockerfiles, no hot reloading)
services:
  redis:
    restart: always
    env_file:
      - .env
    image: redis:6.0.9-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379

  frontend:
    container_name: "disruptors-client"
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - 3000:80

  backend:
    container_name: "disruptors-api"
    build:
      context: ./backend/
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - redis
    command: bash -c "
      uvicorn app.main:app
      --host 0.0.0.0 --port 8080
      --lifespan=on --use-colors --loop uvloop --http httptools
      "

volumes:
  redisdata:
