name: Build

on:
  push:
    branches:
      - "features/**"

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  # Build Dockerfile for the backend (backend/Dockerfile) and run pytest
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Run pytest
        run: |
          cd backend/
          docker build . -t backend
          docker run backend sh -c "pytest"

  # Build main service Dockerfile
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
