name: Build and deploy

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push tag container
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          tags: 
            - ${{ github.repository }}/disruptors/disruptors-api:sha-${{ github.sha }}

  backend-test:
    runs-on: ubuntu-latest
    needs: [backend-build]
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pytest
        run: |
          cd backend/
          docker pull IMAGE
          docker run IMAGE sh -c "pytest"
        env:
          IMAGE: ${{ github.repository }}/disruptors/disruptors-api:sha-${{ github.sha }}

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push tag container
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: 
            - ${{ github.repository }}/disruptors/disruptors-client:sha-${{ github.sha }}

  deploy:
    needs:
      - backend-build
      - backend-test
      - frontend-build

    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Push latest container images
        run: |
          echo "Push api container to latest tag"
          docker pull ${{ github.repository }}/disruptors/disruptors-api:sha-${{ github.sha }}
          docker push ${{ github.repository }}/disruptors/disruptors-api:latest

          echo "Push client container to latest tag"
          docker pull ${{ github.repository }}/disruptors/disruptors-client:sha-${{ github.sha }}
          docker push ${{ github.repository }}/disruptors/disruptors-client:latest

      - name: Trigger the deployment pipline
        run: |
          curl --request POST \
          --form "token=${{ secrets.DEPLOY_TRIGGER_TOKEN }}" \
          -F "variables[ANSIBLE_PLAYBOOK]=disruptors.deploy.yml" \
          --form ref=master "${{ secrets.DEPLOY_TRIGGER_URL }}"
