name: Build and deploy

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile          
          image: disruptors
          tags: latest

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the deployment pipline
        run: |
          curl --request POST \
          --form "token=${{ secrets.DEPLOY_TRIGGER_TOKEN }}" \
          -F "variables[ANSIBLE_PLAYBOOK]=disruptors.deploy.yml" \
          --form ref=master "${{ secrets.DEPLOY_TRIGGER_URL }}"
