name: Build and deploy

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push tag container
        uses: docker/build-push-action@v1
        with:
          context: ./backend
          file: ./backend/Dockerfile
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/disruptors-api
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_with_sha: true
          tag_with_ref: true

  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      # TODO: Probably should just use the image from above
      - name: Run pytest
        run: |
          cd backend/
          docker build . -t backend
          docker run backend sh -c "pytest"

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push tag container
        uses: docker/build-push-action@v1
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/disruptors-client
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_with_sha: true
          tag_with_ref: true

  deploy:
    needs:
      - backend-build
      - backend-test
      - frontend-build

    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Push latest container images
        run: |
          echo "Push api container to latest tag"
          docker pull ${{ github.repository }}/disruptors-client/disruptors-api:sha-${{ github.sha }}
          docker push ${{ github.repository }}/disruptors-client/disruptors-api:latest

          echo "Push client container to latest tag"
          docker pull ${{ github.repository }}/disruptors-client/disruptors-client:sha-${{ github.sha }}
          docker push ${{ github.repository }}/disruptors-client/disruptors-client:latest

      - name: Trigger the deployment pipline
        run: |
          curl --request POST \
          --form "token=${{ secrets.DEPLOY_TRIGGER_TOKEN }}" \
          -F "variables[ANSIBLE_PLAYBOOK]=disruptors.deploy.yml" \
          --form ref=master "${{ secrets.DEPLOY_TRIGGER_URL }}"
